<a href="https://colab.research.google.com/github/Todmount/KHAI_MLcourse/blob/PR2/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика №2
## Робота з NumPy


In [1]:
import numpy as np

1. Створіть вектор (1,2,3) і виведіть його. Виведіть тип масиву.
2. Створіть наступну матрицю і виведіть її:
$$
\left(\begin{array}{cc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$
3. Створіть нульову матрицю розміром (4,5) - див. numpy.zeros.
4. Створіть одиничну матрицю розміром (3,3) - див. numpy.identity.
5. Виведіть розмір матриці, створеної на 2 кроці.
6. Створити дві матриці  $A =
\left(\begin{array}{cc}
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ і $B =
\left(\begin{array}{cc}
-1 & -2 & -3\\
-4 & -5 & -6
\end{array}\right)
$. Виконайте операції додавання і віднімання для цих двох матриць.
7. Для вищезазначених матриць виконайте поелементне множення.
8. До матриці $A$ додайте константу $b=2$.
9. Виконайте множення матриці $\left(\begin{array}{cc}
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ на матрицю $\left(\begin{array}{cc}
1 & 1\\
1 & 1\\
1 & 1
\end{array}\right)
$
10. Для двох векторів $v = (1,2,3)$ і $u = (1,1,1)$ знайти Евклідову норму (див. numpy.linalg.norm)
11. Дано вектор $[11,22,33,44,55]$. Необхідно вивести усі елементи від передостаннього елемента до кінця (використайте зріз).


# Виконання

In [29]:
# Завдання 1
vector = np.array([1, 2, 3])
print("Вектор:", vector)
print("Тип масиву:", type(vector))

Вектор: [1 2 3]
Тип масиву: <class 'numpy.ndarray'>


In [31]:
# Завдання 2
matrix = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print("Матриця:")
print(matrix)

Матриця:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
# Завдання 3
zero_matrix = np.zeros((4, 5))
print("Нульова матриця:")
print(zero_matrix)

Нульова матриця:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
# Завдання 4
identity_matrix = np.identity(3)
print("Одинична матриця:")
print(identity_matrix)

Одинична матриця:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# Завдання 5
matrix_size = matrix.shape
print("Розмір матриці:", matrix_size)

Розмір матриці: (3, 3)


In [40]:
# Завдання 6
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[-1, -2, -3], [-4, -5, -6]])

addition = matrix_A + matrix_B
subtraction = matrix_A - matrix_B

print("Матриця A:")
print(matrix_A)
print("Матриця B:")
print(matrix_B)
print("Додавання матриць A і B:")
print(addition)
print("Віднімання матриць A і B:")
print(subtraction)

Матриця A:
[[1 2 3]
 [4 5 6]]
Матриця B:
[[-1 -2 -3]
 [-4 -5 -6]]
Додавання матриць A і B:
[[0 0 0]
 [0 0 0]]
Віднімання матриць A і B:
[[ 2  4  6]
 [ 8 10 12]]


In [14]:
# Завдання 7
elementwise_multiply = np.multiply(matrix_A, matrix_B)
print("Поелементне множення для матриць A і B:")
print(elementwise_multiply)

Поелементне множення для матриць A і B:
[[ -1  -4  -9]
 [-16 -25 -36]]


In [15]:
# Завдання 8
b = 2
matrix_A_plus_b = matrix_A + b
print("Матриця A плюс константа b:")
print(matrix_A_plus_b)

Матриця A плюс константа b:
[[3 4 5]
 [6 7 8]]


In [39]:
# Завдання 9
matrix_C = np.array([[1, 1], [1, 1], [1, 1]])
matrix_A_multiply_C = np.dot(matrix_A, matrix_C)
print(matrix_A_multiply_C)

[[ 6  6]
 [15 15]]


In [25]:
# Завдання 10
v = np.array([1, 2, 3])
u = np.array([1, 1, 1])
norm_v = np.linalg.norm(v)
norm_u = np.linalg.norm(u)
print("Евклідова норма для вектора v:", norm_v)
print("Евклідова норма для вектора u:", norm_u)

Евклідова норма для вектора v: 3.7416573867739413
Евклідова норма для вектора u: 1.7320508075688772


In [38]:
# Завдання 11
vector_example = np.array([11, 22, 33, 44, 55])
last_two_elements = vector_example[-2:]
print("Елементи від передостаннього до кінця:", last_two_elements)

Елементи від передостаннього до кінця: [44 55]
